/* 家庭互助只展示经审核内容与明确空状态，不伪造用户帖子、评价或客户证言。 */
import { CustomerShell } from "@/components/CustomerShell";
import { Badge } from "@/components/ui/badge";
import { BookOpenCheck, Compass, FileCheck2, LockKeyhole, MessageCircleMore, ShieldCheck } from "lucide-react";
import { Link } from "wouter";

const guides = [
  { title: "冲突后重新开口的三个句式", tag: "平台整理", desc: "练习暂停、复述与共同选择，不把方法包装成适用于所有家庭的答案。" },
  { title: "家庭小记怎样保护孩子隐私", tag: "隐私指南", desc: "在分享之前移除姓名、学校、面部、位置和可识别的时间线索。" },
  { title: "怎样区分一个观点和一个事实", tag: "社区规则", desc: "作者感受、评论观点和可核验事实会使用不同标记，避免把经验当结论。" },
];

export default function Community() { return <CustomerShell><div className="mx-auto max-w-6xl px-5 py-8 sm:px-8 lg:py-10"><div className="grid gap-8 lg:grid-cols-[1.05fr_.95fr]"><div><Badge className="border-0 bg-[#EAF1FF] text-[#2563EB]"><Compass className="mr-1.5 h-3.5 w-3.5" />家庭互助</Badge><h1 className="mt-4 font-story text-4xl font-black leading-tight sm:text-5xl">不是晒结果，<br />是交换真实经验。</h1><p className="mt-4 max-w-xl leading-8 text-slate-600">公开区域只承载经审核、去标识化的家庭经验。当前未连接社区 API，因此不展示任何虚构帖子、互动数或用户评价。</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/moments" className="rounded-full bg-[#F28C45] px-6 py-3.5 text-sm font-bold text-white">先写一份家庭私有小记</Link><button className="rounded-full border border-[#D8E4FF] bg-white px-6 py-3.5 text-sm font-bold text-[#2563EB]">查看发布规则</button></div></div><div className="rounded-[34px] border border-dashed border-[#C7D6F5] bg-[#F7FAFF] p-8 text-center"><span className="mx-auto grid h-16 w-16 place-items-center rounded-3xl bg-white text-[#2563EB] shadow-sm"><MessageCircleMore className="h-7 w-7" /></span><h2 className="mt-5 font-story text-2xl font-bold">经审核经验流暂未连接</h2><p className="mt-3 text-sm leading-7 text-slate-500">未来内容必须经过可见性确认和人工审核；不会根据孩子画像自动推荐商业内容。</p></div></div>
    <div className="mt-12 flex items-center justify-between"><h2 className="font-story text-2xl font-bold">先了解社区边界</h2><span className="text-xs font-bold text-[#2563EB]">平台知识 · 非用户评价</span></div><div className="mt-5 grid gap-4 md:grid-cols-3">{guides.map((guide, index) => <article key={guide.title} className="rounded-[28px] bg-white p-6 shadow-[0_16px_45px_rgba(16,33,62,.06)]"><span className={`grid h-12 w-12 place-items-center rounded-2xl ${index === 0 ? "bg-[#FFF1E6] text-[#F28C45]" : index === 1 ? "bg-[#E6F5F1] text-[#16866D]" : "bg-[#EAF1FF] text-[#2563EB]"}`}>{index === 0 ? <BookOpenCheck className="h-5 w-5" /> : index === 1 ? <LockKeyhole className="h-5 w-5" /> : <FileCheck2 className="h-5 w-5" />}</span><Badge variant="outline" className="mt-5 border-[#EADFD3] text-slate-500">{guide.tag}</Badge><h3 className="mt-3 font-story text-xl font-bold leading-8">{guide.title}</h3><p className="mt-3 text-sm leading-7 text-slate-500">{guide.desc}</p></article>)}</div><div className="mt-8 flex items-start gap-3 rounded-[26px] bg-[#10213E] p-5 text-white"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-[#8EB2FF]" /><div><strong className="text-sm">未成年人商业保护</strong><p className="mt-1 text-xs leading-6 text-slate-300">社区不根据未成年人画像进行自动化营销，也不会把家庭互动转化为公开等级。</p></div></div></div></CustomerShell>; }
