/* 权益与家庭工作台合并成员、角色、同意、会员和资产；体验模式不制造已购买权益。 */
import { CustomerShell } from "@/components/CustomerShell";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { Switch } from "@/components/ui/switch";
import { ChevronRight, Database, FileBox, KeyRound, LockKeyhole, ShieldCheck, UserRound, UsersRound, WalletCards } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

export default function FamilyWorkspace() {
  const [tab, setTab] = useState<"family" | "consent" | "assets">("family");
  const [serviceConsent, setServiceConsent] = useState(true);
  const [mediaConsent, setMediaConsent] = useState(false);
  const toggle = (setter: (value: boolean) => void, value: boolean) => { setter(value); toast("体验交互已更新", { description: "未连接 Consent API，不会改变真实授权。" }); };
  return <CustomerShell><div className="mx-auto max-w-6xl px-5 py-8 sm:px-8 lg:py-10"><section className="relative overflow-hidden rounded-[36px] bg-[#10213E] p-6 text-white sm:p-9"><div className="absolute -right-16 -top-20 h-72 w-72 rounded-full bg-[#2563EB]/35 blur-2xl" /><div className="relative flex flex-col justify-between gap-8 md:flex-row md:items-end"><div><Badge className="border-white/15 bg-white/10 text-white">家庭私有空间 · 体验数据</Badge><h1 className="mt-4 font-story text-4xl font-black">林家的权益与家庭</h1><p className="mt-3 text-sm text-slate-300">成员、角色、授权、计划意向和可核验资产在这里分开管理。</p></div><div className="flex -space-x-3"><Avatar className="h-12 w-12 border-3 border-[#10213E]"><AvatarFallback className="bg-[#FFF1E6] font-bold text-[#F28C45]">林</AvatarFallback></Avatar><Avatar className="h-12 w-12 border-3 border-[#10213E]"><AvatarFallback className="bg-[#EAF1FF] font-bold text-[#2563EB]">宇</AvatarFallback></Avatar><span className="grid h-12 w-12 place-items-center rounded-full border-3 border-[#10213E] bg-white/10 text-xs font-bold">+1</span></div></div></section>
    <div className="mt-6 grid gap-6 lg:grid-cols-[240px_1fr]"><aside className="h-fit rounded-[28px] bg-white p-3 shadow-[0_16px_45px_rgba(16,33,62,.06)]">{[["family","家庭成员",UsersRound],["consent","隐私与同意",ShieldCheck],["assets","权益与资产",WalletCards]].map(([id,label,Icon]) => <button key={String(id)} onClick={() => setTab(id as typeof tab)} className={`flex w-full items-center gap-3 rounded-2xl px-4 py-3.5 text-sm font-bold ${tab === id ? "bg-[#10213E] text-white" : "text-slate-500 hover:bg-[#FFF9F3]"}`}><Icon className={`h-5 w-5 ${tab === id ? "text-[#F28C45]" : ""}`} />{String(label)}</button>)}</aside>
    <section>{tab === "family" && <div className="space-y-4"><Header title="家庭成员与角色" desc="角色决定谁可以看见、确认和管理家庭信息。" />{[["林女士","家庭管理员","林"],["小宇","家庭成员 · 9 岁","宇"],["周先生","共同照护人","周"]].map(([name,role,initial],index) => <button key={name} className="flex w-full items-center gap-4 rounded-[26px] bg-white p-5 text-left shadow-[0_14px_40px_rgba(16,33,62,.05)]"><Avatar className="h-12 w-12"><AvatarFallback className={index === 0 ? "bg-[#FFF1E6] text-[#F28C45]" : "bg-[#EAF1FF] text-[#2563EB]"}>{initial}</AvatarFallback></Avatar><span className="min-w-0 flex-1"><strong className="block">{name}</strong><small className="mt-1 block text-slate-500">{role}</small></span><ChevronRight className="h-5 w-5 text-slate-300" /></button>)}</div>}
    {tab === "consent" && <div><Header title="隐私与同意" desc="每一种用途单独授权；撤回应立即阻止新的处理。" /><div className="space-y-4"><ConsentRow icon={UserRound} title="家庭成长支持" desc="用于测评、计划和今日行动；仅在家庭范围内处理。" checked onChange={() => toast("核心家庭上下文授权需由家庭管理员在真实 API 中管理")} fixed /><ConsentRow icon={ShieldCheck} title="专业服务匹配" desc="用于本次咨询和活动意向，可随时撤回。" checked={serviceConsent} onChange={(value) => toggle(setServiceConsent,value)} /><ConsentRow icon={LockKeyhole} title="媒体辅助理解" desc="允许在主动提交后处理语音、照片和短视频。" checked={mediaConsent} onChange={(value) => toggle(setMediaConsent,value)} /></div><div className="mt-5 rounded-[24px] border border-[#D9E4FF] bg-[#F3F7FF] p-4 text-xs leading-6 text-[#5071AE]"><strong className="text-[#1D4EAE]">数据最小化</strong><br />未提交的本地草稿不会发送；AI 分析必须记录模型、提示版本、上下文快照和人工确认。</div></div>}
    {tab === "assets" && <div><Header title="权益与资产" desc="只展示可由正式后端核验的订阅、权益和方案意向。" /><div className="grid gap-4 sm:grid-cols-2"><AssetCard icon={WalletCards} title="会员与权益" desc="未连接 Membership Projection" /><AssetCard icon={FileBox} title="方案意向" desc="未连接 Order Intent Projection" /><AssetCard icon={Database} title="家庭报告" desc="没有已确认的报告资产" /><AssetCard icon={KeyRound} title="服务额度" desc="未连接 Benefit Ledger" /></div><div className="mt-5 rounded-[26px] bg-[#FFF1E6] p-5 text-sm leading-7 text-slate-600">这里不会显示硬编码积分、虚构余额或默认会员等级。真实定价、支付和权益兑换需在 Commerce 域与未成年人商业权限规则完成后开放。</div></div>}</section></div></div></CustomerShell>;
}

function Header({ title, desc }: { title: string; desc: string }) { return <div className="mb-5"><h2 className="font-story text-3xl font-black">{title}</h2><p className="mt-2 text-sm text-slate-500">{desc}</p></div>; }
function ConsentRow({ icon: Icon, title, desc, checked, onChange, fixed = false }: { icon: typeof ShieldCheck; title: string; desc: string; checked: boolean; onChange: (value: boolean) => void; fixed?: boolean }) { return <div className="flex items-start gap-4 rounded-[26px] bg-white p-5 shadow-[0_14px_40px_rgba(16,33,62,.05)]"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-[#EAF1FF] text-[#2563EB]"><Icon className="h-5 w-5" /></span><div className="min-w-0 flex-1"><strong>{title}</strong><p className="mt-1 text-sm leading-6 text-slate-500">{desc}</p>{fixed && <Badge variant="outline" className="mt-2 border-[#D8E4FF] text-[#2563EB]">核心授权</Badge>}</div><Switch checked={checked} onCheckedChange={onChange} /></div>; }
function AssetCard({ icon: Icon, title, desc }: { icon: typeof WalletCards; title: string; desc: string }) { return <div className="rounded-[26px] bg-white p-5 shadow-[0_14px_40px_rgba(16,33,62,.05)]"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-[#FFF1E6] text-[#F28C45]"><Icon className="h-5 w-5" /></span><h3 className="mt-4 font-bold">{title}</h3><p className="mt-2 text-sm text-slate-500">{desc}</p><button className="mt-4 text-xs font-bold text-[#2563EB]">查看数据要求</button></div>; }
