/* 成长旅程只呈现阶段、行动和复盘，不将家庭成长压缩为总分。 */
import { CustomerShell } from "@/components/CustomerShell";
import { Badge } from "@/components/ui/badge";
import { Check, ChevronRight, Circle, Flag, LockKeyhole, MessageCircleHeart, Route } from "lucide-react";

const stages = [
  { title: "看见彼此", subtitle: "完成家庭测评与第一次共同确认", state: "done", meta: "已完成 · 8 月 12 日" },
  { title: "先听，再回应", subtitle: "21 天倾听练习与每周复盘", state: "active", meta: "进行中 · 第 7 天" },
  { title: "一起做决定", subtitle: "把争执转化为可以共同选择的行动", state: "next", meta: "下一阶段" },
  { title: "形成家庭节奏", subtitle: "找到适合你们自己的长期方式", state: "locked", meta: "完成前序阶段后开启" },
];

export default function Journey() { return <CustomerShell><div className="mx-auto max-w-5xl px-5 py-8 sm:px-8 lg:py-12"><div className="enter-rise grid gap-8 lg:grid-cols-[1fr_.75fr]"><div><Badge className="border-0 bg-[#EAF1FF] text-[#2563EB]"><Route className="mr-1.5 h-3.5 w-3.5" />90 天家庭成长旅程</Badge><h1 className="mt-4 font-story text-4xl font-black sm:text-5xl">你们正在走的，<br />不是一张成绩单。</h1><p className="mt-4 max-w-xl leading-7 text-slate-600">每个阶段都由家庭确认，每个行动都可以调整。AI 只提供建议，决定权始终在你们手中。</p></div><div className="relative overflow-hidden rounded-[30px] bg-[#F28C45] p-6 text-white shadow-xl shadow-orange-200"><div className="absolute -right-10 -top-10 h-36 w-36 rounded-full bg-white/15" /><div className="relative"><p className="text-xs font-bold text-white/75">当前阶段</p><h2 className="mt-2 font-story text-3xl font-bold">先听，再回应</h2><p className="mt-3 text-sm leading-6 text-white/80">已完成 7 个家庭行动，还有 14 天进入阶段复盘。</p><div className="mt-6 h-2 overflow-hidden rounded-full bg-white/25"><div className="h-full w-1/3 rounded-full bg-white" /></div></div></div></div>
    <div className="relative mt-12 space-y-4 before:absolute before:left-[25px] before:top-8 before:h-[calc(100%-64px)] before:w-px before:bg-[#E3D5C8] sm:before:left-[33px]">{stages.map((stage, index) => <div key={stage.title} className={`relative flex gap-4 rounded-[28px] p-4 transition-transform hover:-translate-y-0.5 sm:gap-6 sm:p-6 ${stage.state === "active" ? "bg-[#10213E] text-white shadow-xl shadow-slate-300" : "bg-white shadow-[0_12px_36px_rgba(16,33,62,.06)]"}`}><span className={`relative z-10 grid h-12 w-12 shrink-0 place-items-center rounded-2xl sm:h-16 sm:w-16 ${stage.state === "done" ? "bg-[#E6F5F1] text-[#16866D]" : stage.state === "active" ? "bg-[#F28C45] text-white" : stage.state === "locked" ? "bg-slate-100 text-slate-400" : "bg-[#FFF1E6] text-[#F28C45]"}`}>{stage.state === "done" ? <Check /> : stage.state === "active" ? <Flag /> : stage.state === "locked" ? <LockKeyhole /> : <Circle />}</span><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><div><p className={`text-xs font-bold ${stage.state === "active" ? "text-[#8EB2FF]" : "text-slate-400"}`}>阶段 {index + 1}</p><h2 className="mt-1 font-story text-xl font-bold sm:text-2xl">{stage.title}</h2></div>{stage.state !== "locked" && <ChevronRight className="mt-2 h-5 w-5 shrink-0 opacity-50" />}</div><p className={`mt-2 text-sm leading-6 ${stage.state === "active" ? "text-slate-300" : "text-slate-500"}`}>{stage.subtitle}</p><p className={`mt-3 text-xs font-semibold ${stage.state === "done" ? "text-[#16866D]" : stage.state === "active" ? "text-[#FFC092]" : "text-slate-400"}`}>{stage.meta}</p></div></div>)}</div>
    <div className="mt-8 flex items-center gap-4 rounded-[28px] border border-[#D9E4FF] bg-[#F3F7FF] p-5 text-[#1D4EAE]"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-white"><MessageCircleHeart className="h-6 w-6" /></span><div><strong>下一次阶段复盘由家长发起</strong><p className="mt-1 text-sm text-[#5071AE]">系统不会自动升级阶段，也不会根据孩子表现生成排名。</p></div></div></div></CustomerShell>; }
