/* 理解家庭工作台合并测评入口、版本化作答、假设解读和家庭确认，不使用诊断或评分语义。 */
import { CustomerShell } from "@/components/CustomerShell";
import { Badge } from "@/components/ui/badge";
import { Check, CheckCircle2, ChevronRight, Clock3, FileText, Lightbulb, LockKeyhole, ShieldCheck, Sparkles } from "lucide-react";
import { useState } from "react";
import { Link } from "wouter";
import { toast } from "sonner";

const questions = [
  { title: "当孩子拒绝一个安排时，你们最近更像哪种情况？", options: ["会争执很久，很难停下来", "可以暂停，但之后不太会再谈", "偶尔能一起找到折中办法"] },
  { title: "需要开始学习或收起手机时，孩子通常怎么回应？", options: ["需要多次提醒才行动", "会先表达不满，再慢慢行动", "大多能按约定开始"] },
  { title: "发生冲突后，你最希望先改变什么？", options: ["减少彼此提高音量", "先听完再回应", "一起建立更清楚的约定"] },
];

export default function Understand() {
  const [step, setStep] = useState(0);
  const [questionIndex, setQuestionIndex] = useState(0);
  const [answers, setAnswers] = useState<Record<number, number>>({});
  const [decision, setDecision] = useState<"CONFIRM" | "DISMISS" | null>(null);
  const current = questions[questionIndex];
  const nextQuestion = () => {
    if (answers[questionIndex] === undefined) return toast.error("请选择最贴近最近情况的一项");
    if (questionIndex < questions.length - 1) setQuestionIndex((value) => value + 1);
    else setStep(2);
  };
  return <CustomerShell><div className="mx-auto max-w-6xl px-5 py-8 sm:px-8 lg:py-10"><div className="mb-7 flex flex-wrap items-center justify-between gap-4"><div><Badge className="border-0 bg-[#EAF1FF] text-[#2563EB]"><Lightbulb className="mr-1.5 h-3.5 w-3.5" />理解家庭</Badge><h1 className="mt-3 font-story text-3xl font-black sm:text-4xl">先理解正在发生什么，再决定下一步。</h1></div><Badge variant="outline" className="border-[#D8E4FF] bg-white text-[#2563EB]">体验数据模式</Badge></div>
    <div className="grid gap-6 lg:grid-cols-[280px_1fr]"><aside className="h-fit rounded-[30px] bg-white p-5 shadow-[0_18px_50px_rgba(16,33,62,.06)]"><p className="text-xs font-bold text-slate-400">本次理解流程</p><div className="mt-5 space-y-5">{["确认对象与边界", "回答最近的家庭场景", "审阅成长假设", "由家长确认方向"].map((label, index) => <div key={label} className="flex gap-3"><span className={`grid h-8 w-8 shrink-0 place-items-center rounded-full text-xs font-bold ${step > index ? "bg-[#16866D] text-white" : step === index ? "bg-[#F28C45] text-white" : "bg-slate-100 text-slate-400"}`}>{step > index ? <Check className="h-4 w-4" /> : index + 1}</span><div><strong className={`text-sm ${step === index ? "text-[#10213E]" : "text-slate-500"}`}>{label}</strong>{index === 2 && <small className="mt-1 block text-slate-400">AI 只生成假设</small>}</div></div>)}</div><div className="mt-6 rounded-2xl bg-[#F3F7FF] p-4 text-xs leading-5 text-[#5071AE]"><ShieldCheck className="mb-2 h-4 w-4 text-[#2563EB]" />不会生成孩子分数、家庭排名或诊断结论。</div></aside>
    <section className="min-h-[570px] overflow-hidden rounded-[34px] bg-white shadow-[0_24px_70px_rgba(16,33,62,.08)]">
      {step === 0 && <div className="grid min-h-[570px] lg:grid-cols-[1.05fr_.95fr]"><div className="p-7 sm:p-10"><Badge className="border-0 bg-[#FFF1E6] text-[#D66A27]">约 3 分钟</Badge><h2 className="mt-5 font-story text-4xl font-black leading-tight">从最近发生过的<br />真实场景开始。</h2><p className="mt-5 max-w-lg leading-8 text-slate-600">这不是给孩子做测试。我们会从家庭互动中整理一个可供你确认的成长假设。</p><div className="mt-8 space-y-3"><Boundary icon={LockKeyhole} text="只用于这个家庭的成长支持" /><Boundary icon={FileText} text="答案保存为版本化过程证据" /><Boundary icon={Sparkles} text="AI 输出不会自动成为家庭事实" /></div><button onClick={() => setStep(1)} className="mt-9 flex h-13 items-center gap-2 rounded-full bg-[#F28C45] px-7 text-sm font-bold text-white shadow-lg shadow-orange-200">开始选择场景<ChevronRight className="h-4 w-4" /></button></div><div className="relative min-h-72 overflow-hidden bg-[#FFF1E6]"><img src="/manus-storage/aifamily-hero-reference_326fab45.jpg" alt="家庭共同完成小行动" className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-[#10213E]/65 to-transparent" /><div className="absolute bottom-7 left-7 right-7 text-white"><p className="text-xs font-semibold text-white/70">本次对象</p><h3 className="mt-1 font-story text-2xl font-bold">小宇 · 9 岁</h3><p className="mt-2 text-sm text-white/75">由家庭管理员林女士发起</p></div></div></div>}
      {step === 1 && <div className="p-7 sm:p-10"><div className="flex items-center justify-between"><div className="flex items-center gap-2 text-xs font-bold text-[#2563EB]"><Clock3 className="h-4 w-4" />最近两周</div><span className="font-score text-sm font-extrabold text-[#10213E]">{questionIndex + 1} / {questions.length}</span></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-[#EAF1FF]"><div className="h-full rounded-full bg-[#2563EB] transition-all" style={{ width: `${((questionIndex + 1) / questions.length) * 100}%` }} /></div><h2 className="mt-10 max-w-3xl font-story text-3xl font-black leading-relaxed sm:text-4xl">{current.title}</h2><div className="mt-8 grid gap-3">{current.options.map((option, index) => <button key={option} onClick={() => setAnswers((value) => ({ ...value, [questionIndex]: index }))} className={`flex items-center justify-between rounded-[22px] border p-5 text-left text-sm font-semibold ${answers[questionIndex] === index ? "border-[#2563EB] bg-[#F3F7FF] text-[#184FBF] shadow-sm" : "border-[#EADFD3] bg-white text-[#10213E] hover:border-[#F4C8A9] hover:bg-[#FFF9F3]"}`}><span>{option}</span><span className={`grid h-6 w-6 place-items-center rounded-full border ${answers[questionIndex] === index ? "border-[#2563EB] bg-[#2563EB] text-white" : "border-slate-300"}`}>{answers[questionIndex] === index && <Check className="h-3.5 w-3.5" />}</span></button>)}</div><div className="mt-8 flex items-center justify-between"><button onClick={() => questionIndex > 0 ? setQuestionIndex((v) => v - 1) : setStep(0)} className="text-sm font-semibold text-slate-500">返回</button><button onClick={nextQuestion} className="flex h-12 items-center gap-2 rounded-full bg-[#F28C45] px-6 text-sm font-bold text-white">{questionIndex === questions.length - 1 ? "生成待确认假设" : "下一题"}<ChevronRight className="h-4 w-4" /></button></div></div>}
      {step === 2 && <div className="p-7 sm:p-10"><div className="flex flex-wrap items-center justify-between gap-3"><Badge className="border-0 bg-[#EAF1FF] text-[#2563EB]"><Sparkles className="mr-1.5 h-3.5 w-3.5" />AI 协助生成 · DRAFT</Badge><button className="text-xs font-bold text-[#2563EB]">查看依据与来源</button></div><h2 className="mt-6 font-story text-4xl font-black">一个待你确认的成长假设</h2><div className="mt-7 rounded-[28px] bg-[#10213E] p-6 text-white sm:p-8"><p className="text-xs font-bold text-[#8EB2FF]">PERSPECTIVE · 不是诊断</p><p className="mt-4 font-story text-2xl font-bold leading-10">当对话很快进入“立刻解决问题”时，孩子可能更需要先确认自己的表达被听见。</p><p className="mt-5 text-sm leading-7 text-slate-300">建议先尝试 7 天“先听完，再回应”的三分钟行动，并在阶段复盘时由你判断是否继续。</p></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><Evidence title="你提供的场景" value="3 项" /><Evidence title="适用边界" value="家庭沟通" /><Evidence title="置信表达" value="需家长确认" /></div><div className="mt-8 flex flex-wrap gap-3"><button onClick={() => { setDecision("CONFIRM"); setStep(3); }} className="rounded-full bg-[#F28C45] px-6 py-3.5 text-sm font-bold text-white">这个方向贴近我们</button><button onClick={() => { setDecision("DISMISS"); setStep(3); }} className="rounded-full border border-[#D8E4FF] bg-white px-6 py-3.5 text-sm font-bold text-[#2563EB]">暂时不认同</button></div></div>}
      {step === 3 && <div className="grid min-h-[570px] place-items-center p-7 text-center sm:p-10"><div className="max-w-xl"><span className={`mx-auto grid h-20 w-20 place-items-center rounded-full ${decision === "CONFIRM" ? "bg-[#E6F5F1] text-[#16866D]" : "bg-[#EAF1FF] text-[#2563EB]"}`}><CheckCircle2 className="h-10 w-10" /></span><p className="mt-6 text-xs font-bold text-slate-400">已形成家庭确认回执</p><h2 className="mt-3 font-story text-4xl font-black">{decision === "CONFIRM" ? "成长方向由你确认了。" : "你的不同意见也被保留。"}</h2><p className="mt-4 leading-8 text-slate-600">{decision === "CONFIRM" ? "系统可以据此准备一个可调整的 90 天计划草案；它仍需由家庭确认后才生效。" : "系统不会据此创建成长计划，你可以稍后重新测评或补充更多家庭场景。"}</p>{decision === "CONFIRM" ? <Link href="/journey" className="mt-8 inline-flex h-13 items-center gap-2 rounded-full bg-[#F28C45] px-7 text-sm font-bold text-white">查看计划草案<ChevronRight className="h-4 w-4" /></Link> : <button onClick={() => { setStep(1); setQuestionIndex(0); }} className="mt-8 rounded-full bg-[#2563EB] px-7 py-3.5 text-sm font-bold text-white">重新整理场景</button>}</div></div>}
    </section></div></div></CustomerShell>;
}

function Boundary({ icon: Icon, text }: { icon: typeof LockKeyhole; text: string }) { return <div className="flex items-center gap-3 text-sm text-slate-600"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#F3F7FF] text-[#2563EB]"><Icon className="h-4 w-4" /></span>{text}</div>; }
function Evidence({ title, value }: { title: string; value: string }) { return <div className="rounded-2xl bg-[#FFF9F3] p-4"><p className="text-xs text-slate-500">{title}</p><strong className="mt-1 block text-sm">{value}</strong></div>; }
