"""FamilyTaskContext (AIFAMILY-WM-005B, PART D).

The Agent-facing, structured, immutable output of Task Context Projection —
what an Agent actually receives, never the raw `FamilyBeliefState`. Every
item keeps its full epistemic semantics (predicate, epistemic_kind, support/
contradiction/uncertainty) rather than collapsing into an untyped string —
see `FamilyContextItem`'s docstring for why this is an R9 boundary, not a
style preference.

`FamilyTaskContext` is ephemeral: it is not a business record and is never
persisted to its own table (AIFAMILY-WM-005B PART Q). It is built fresh from
a `FamilyBeliefState` for one task, one use_case, one `TaskContextSpec`.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime

from .contracts import ContextContractError, ContextScope
from .world_state import WorldStateActorType, WorldStateEpistemicKind


@dataclass(frozen=True, slots=True)
class FamilyContextItem:
    """One selected piece of family cognition, epistemic type intact.

    Deliberately not `ContextSnapshot`'s `StateObservation` (which only
    carries `dimension`/`observed_value`/`evidence_refs`, with no concept of
    FACT vs SELF_REPORT vs PERSPECTIVE vs HYPOTHESIS, nor of support/
    contradiction/uncertainty) — collapsing a HYPOTHESIS into an untyped
    observation would let it read exactly like settled fact once it reaches
    an Agent, which is precisely the R9 boundary `world_state.py` was built
    to make structurally impossible. This dataclass is the projection-time
    equivalent of `WorldStateAtom`, not a replacement vocabulary.
    """

    item_ref: str
    subject_ids: tuple[str, ...]
    predicate: str
    epistemic_kind: WorldStateEpistemicKind
    value_ref: str
    asserted_by: str
    attributed_actor_type: WorldStateActorType
    source_refs: tuple[str, ...]
    evidence_refs: tuple[str, ...]
    provenance: str
    recorded_at: datetime
    support_level: str | None = None
    contradiction_level: str | None = None
    uncertainty: str | None = None
    #: AIFAMILY-WM-005B PART I: why this item was selected — never
    #: generated by a model, always one of a small, deterministic set of
    #: reasons the Projector itself assigns (see `task_context_projector.py`).
    selection_reason: str = ""

    def __post_init__(self) -> None:
        if not self.item_ref.strip():
            raise ContextContractError("FAMILY_CONTEXT_ITEM_REF_REQUIRED")
        if not self.predicate.strip():
            raise ContextContractError("FAMILY_CONTEXT_ITEM_PREDICATE_REQUIRED")
        if self.epistemic_kind is WorldStateEpistemicKind.HYPOTHESIS and (
            self.support_level is None
            or self.contradiction_level is None
            or self.uncertainty is None
        ):
            raise ContextContractError("FAMILY_CONTEXT_ITEM_HYPOTHESIS_REQUIRES_BELIEF_METADATA")


@dataclass(frozen=True, slots=True)
class FamilyContextConflict:
    """A conflict pair, kept whole — never one side without the other.

    `atom_item_refs` always has length 2: see `task_context_projector.py`'s
    fail-closed rule that a conflict pair is either both included or both
    excluded, never split.
    """

    conflict_ref: str
    predicate: str
    atom_item_refs: tuple[str, str]
    conflict_type: str

    def __post_init__(self) -> None:
        if len(self.atom_item_refs) != 2:
            raise ContextContractError("FAMILY_CONTEXT_CONFLICT_REQUIRES_TWO_ITEM_REFS")


@dataclass(frozen=True, slots=True)
class FamilyContextUnknown:
    """An effective open Unknown, carried through with its full shape —
    never reduced to just the question text."""

    unknown_ref: str
    question: str
    why_it_matters: str
    target_predicate: str | None
    priority: str
    blocking_refs: tuple[str, ...]
    preferred_source: str | None = None


@dataclass(frozen=True, slots=True)
class FamilyTaskContext:
    """Immutable, scope-checked, ephemeral Agent input.

    `context_ref` is designed to be usable as `AgentTask.context_snapshot_ref`
    (AIFAMILY-WM-005B PART K) without this dataclass depending on
    `agent_runtime` at all — the mapping is the caller's responsibility, via
    `to_structured_payload()`.
    """

    context_ref: str
    scope: ContextScope
    use_case: str
    read_at: datetime
    expires_at: datetime
    items: tuple[FamilyContextItem, ...]
    conflicts: tuple[FamilyContextConflict, ...]
    unknowns: tuple[FamilyContextUnknown, ...]
    source_refs: tuple[str, ...]
    provenance: str

    def __post_init__(self) -> None:
        if not self.context_ref.strip():
            raise ContextContractError("FAMILY_TASK_CONTEXT_REF_REQUIRED")
        if not self.use_case.strip():
            raise ContextContractError("FAMILY_TASK_CONTEXT_USE_CASE_REQUIRED")
        if self.expires_at <= self.read_at:
            raise ContextContractError("FAMILY_TASK_CONTEXT_EXPIRES_AT_MUST_FOLLOW_READ_AT")
        item_refs = {item.item_ref for item in self.items}
        for conflict in self.conflicts:
            if not set(conflict.atom_item_refs).issubset(item_refs):
                raise ContextContractError("FAMILY_CONTEXT_CONFLICT_REFERENCES_UNKNOWN_ITEM")

    def explain_item(self, item_ref: str) -> dict[str, object]:
        """A pure, structured explain record — never LLM-generated (PART I)."""

        for item in self.items:
            if item.item_ref == item_ref:
                return {
                    "item_ref": item.item_ref,
                    "predicate": item.predicate,
                    "epistemic_kind": item.epistemic_kind.value,
                    "selection_reason": item.selection_reason,
                    "source_refs": item.source_refs,
                    "evidence_refs": item.evidence_refs,
                    "provenance": item.provenance,
                }
        raise ContextContractError(f"FAMILY_CONTEXT_ITEM_NOT_FOUND:{item_ref}")

    def to_structured_payload(self) -> dict[str, object]:
        """Deterministic mapping onto a plain dict an `AgentTask.payload`
        can carry — never drops `epistemic_kind`/belief metadata (PART K)."""

        return {
            "context_ref": self.context_ref,
            "use_case": self.use_case,
            "read_at": self.read_at.isoformat(),
            "expires_at": self.expires_at.isoformat(),
            "items": [
                {
                    "item_ref": item.item_ref,
                    "subject_ids": list(item.subject_ids),
                    "predicate": item.predicate,
                    "epistemic_kind": item.epistemic_kind.value,
                    "value_ref": item.value_ref,
                    "asserted_by": item.asserted_by,
                    "attributed_actor_type": item.attributed_actor_type.value,
                    "support_level": item.support_level,
                    "contradiction_level": item.contradiction_level,
                    "uncertainty": item.uncertainty,
                    "source_refs": list(item.source_refs),
                    "evidence_refs": list(item.evidence_refs),
                }
                for item in self.items
            ],
            "conflicts": [
                {
                    "conflict_ref": c.conflict_ref,
                    "predicate": c.predicate,
                    "atom_item_refs": list(c.atom_item_refs),
                    "conflict_type": c.conflict_type,
                }
                for c in self.conflicts
            ],
            "unknowns": [
                {
                    "unknown_ref": u.unknown_ref,
                    "question": u.question,
                    "why_it_matters": u.why_it_matters,
                    "target_predicate": u.target_predicate,
                    "priority": u.priority,
                    "blocking_refs": list(u.blocking_refs),
                    "preferred_source": u.preferred_source,
                }
                for u in self.unknowns
            ],
            "source_refs": list(self.source_refs),
        }


__all__ = [
    "FamilyContextConflict",
    "FamilyContextItem",
    "FamilyContextUnknown",
    "FamilyTaskContext",
]
