import type {
  ProductPackageReviewInput,
  ProductPackageReviewResponse,
} from "./productPackageReviewApi";

const HASH_A = "a".repeat(64);
const HASH_B = "b".repeat(64);
const HASH_C = "c".repeat(64);

export const sampleProductPackageReviewInput: ProductPackageReviewInput = {
  source_draft_locator: "model-draft-locator:one",
  concept_id: "concept:one",
  zone_assessment_id: "assessment:one",
  product_kind: "MICRO_CAMP",
  duration_days: 21,
  primary_contradiction: "理解与行动之间存在断点",
  demand_ref: "demand:one",
  market_insight_refs: ["insight:one"],
  competitor_evidence_refs: ["competitor-evidence:one"],
  component_ids: ["component:understand:v1", "component:action:v1"],
  skill_ids: ["skill:compose:v1"],
  success_metric_ids: ["metric:action-adoption"],
  guardrail_ids: ["guardrail:consent"],
  stop_conditions: ["stop:safety"],
  pause_policy: "家长可随时暂停",
  human_gate_policy: "敏感建议需人工复核",
  evidence_locators: ["verification-receipt:market"],
  assumptions: ["需要小批家庭验证"],
  unknowns: ["不同年龄段的节奏差异"],
  next_validation: "完成五个家庭的匿名试点",
  requested_ttl_hours: 24,
};

export const sampleProductPackageReviewResponse: ProductPackageReviewResponse = {
  lifecycle_state: "SUBMITTED_FOR_REVIEW",
  replayed: false,
  etag: `"${HASH_C}"`,
  draft: {
    schema_version: "1.2",
    version: "1.2.0",
    status: "DRAFT",
    draft_id: "product-package-draft:one",
    version_id: "product-package-version:one",
    concept_id: "concept:one",
    zone_assessment_id: "assessment:one",
    approved_zone: "UNIQUE",
    product_kind: "MICRO_CAMP",
    duration_days: 21,
    primary_contradiction: "理解与行动之间存在断点",
    demand_ref: "demand:one",
    market_insight_refs: ["insight:one"],
    competitor_evidence_refs: ["competitor-evidence:one"],
    component_ids: ["component:understand:v1", "component:action:v1"],
    skill_ids: ["skill:compose:v1"],
    success_metric_ids: ["metric:action-adoption"],
    guardrail_ids: ["guardrail:consent"],
    stop_conditions: ["stop:safety"],
    pause_policy: "家长可随时暂停",
    human_gate_policy: "敏感建议需人工复核",
    evidence_refs: ["verification-receipt:market"],
    evidence_admissions: [{
      admission_status: "ADMITTED",
      reason_codes: [],
      claim_type: "MARKET_EXISTENCE",
      required_claim_refs: ["claim:market"],
      required_applicability_refs: ["role:PARENT_GUARDIAN", "age:AGE_9_12"],
      receipt_id: "verification-receipt:market",
      receipt_hash: HASH_A,
      evidence_id: "evidence:market:one",
      evidence_version: 1,
      evidence_record_hash: HASH_B,
      evidence_ref: "source:market:one",
      claim_scope: ["claim:market"],
      applicability_scope: ["role:PARENT_GUARDIAN", "age:AGE_9_12", "region:CN"],
      criteria_refs: ["evidence-policy:source-integrity:v1"],
      verification_methods: ["SOURCE_OPENED", "EVIDENCE_RECORD_HASH_MATCHED"],
      verification_purpose: "product_package_admission",
      verification_policy_version: "product-evidence-verification:v1",
      receipt_outcome: "VERIFIED",
      integrity_check: "PASS",
      relevance: "RELEVANT",
      task_id: "task:evidence:market",
      proposal_id: "proposal:evidence:market",
      decision_id: "decision:evidence:market",
      verified_at: "2026-08-31T17:00:00Z",
      valid_until: "2026-09-30T18:00:00Z",
      admission_policy_version: "family-education-evidence-admission:v1",
      admitted_at: "2026-08-31T18:00:00Z",
    }],
    assumptions: ["需要小批家庭验证"],
    unknowns: ["不同年龄段的节奏差异"],
    next_validation: "完成五个家庭的匿名试点",
    source_draft_locator: "model-draft-locator:one",
    source_provenance_ref: "model-draft:canonical:one",
    model_ref: "model:test@1",
    prompt_use_case_version: "service-product-composition@1",
    intent_hash: HASH_A,
    resolved_request_hash: HASH_B,
    content_hash: HASH_C,
    created_at: "2026-08-31T18:00:00Z",
    expires_at: "2026-09-01T18:00:00Z",
  },
  review_task: {
    task_id: "human-task:one",
    status: "OPEN",
    proposal_id: "proposal:package:one",
    action_name: "ADOPT_PRODUCT_CONCEPT_AS_DEFINITION",
    risk_level: "MEDIUM",
    provenance_ref: `product-package-draft:product-package-draft:one:${HASH_C}`,
    created_at: "2026-08-31T18:00:00Z",
    expires_at: "2026-09-01T18:00:00Z",
  },
};
