import type { ProductPackageReviewResponse } from "./productPackageReviewApi";
import { sampleProductPackageReviewResponse } from "./productPackageReviewFixtures";
import type { VersionedCatalogSnapshot } from "./productPortfolioModels";

const HASH_D = "d".repeat(64);
const HASH_E = "e".repeat(64);
const HASH_F = "f".repeat(64);

export const secondProductPackageReviewResponse: ProductPackageReviewResponse = {
  ...sampleProductPackageReviewResponse,
  etag: `"${HASH_D}"`,
  draft: {
    ...sampleProductPackageReviewResponse.draft,
    draft_id: "product-package-draft:two",
    version_id: "product-package-version:two",
    concept_id: "concept:two",
    zone_assessment_id: "assessment:two",
    approved_zone: "ADVANTAGE",
    component_ids: ["component:action:v1", "component:weekly-review:v2"],
    skill_ids: ["skill:compose:v1", "skill:reflection:v2"],
    evidence_refs: ["verification-receipt:two"],
    evidence_admissions: [{
      ...sampleProductPackageReviewResponse.draft.evidence_admissions[0],
      receipt_id: "verification-receipt:two",
      evidence_id: "evidence:two",
      decision_id: "decision:evidence:two",
    }],
    content_hash: HASH_D,
  },
  review_task: {
    ...sampleProductPackageReviewResponse.review_task,
    task_id: "human-task:two",
    proposal_id: "proposal:package:two",
    provenance_ref: `product-package-draft:product-package-draft:two:${HASH_D}`,
  },
};

export const sampleCatalogSnapshot: VersionedCatalogSnapshot = {
  schema_version: "1.0",
  snapshot_id: "catalog-snapshot:one",
  content_hash: HASH_E,
  tenant_scope: "tenant:test",
  purpose: "PRODUCT_PACKAGE_COMPOSITION",
  policy_version: "catalog-selection:v1",
  target_context_hash: HASH_F,
  evaluated_for: {
    draft_id: sampleProductPackageReviewResponse.draft.draft_id,
    version: sampleProductPackageReviewResponse.draft.version,
    content_hash: sampleProductPackageReviewResponse.draft.content_hash,
  },
  generated_at: "2026-09-01T00:00:00Z",
  expires_at: "2099-09-08T00:00:00Z",
  items: [
    {
      item_kind: "COMPONENT",
      item_ref: "component:action:v1",
      logical_id: "component:action",
      version: "1.0.0",
      content_hash: HASH_F,
      title: "可暂停的今日行动",
      source_lifecycle_state: "ACTIVE",
      server_selection_state: "REUSABLE",
      reason_codes: [],
      owner_ref: "journey",
      purpose: "把家庭理解转为可暂停的小行动",
      zone: "ADVANTAGE",
      target_roles: ["PARENT_GUARDIAN"],
      executor_roles: ["PRODUCT_OPERATOR"],
      age_bands: ["AGE_9_12"],
      scenarios: ["PARENT_CHILD_COMMUNICATION"],
      regions: ["CN"],
      locales: ["zh-CN"],
      preconditions: ["guardian_consent_active"],
      contraindications: ["active_safety_escalation"],
      admission_receipts: [{ receipt_id: "verification-receipt:market", content_hash: HASH_E, outcome: "ADMITTED", policy_version: "admission:v1", valid_until: "2099-09-08T00:00:00Z" }],
      required_skill_refs: ["skill:compose:v1"],
      allowed_tools: ["read_component_catalog"],
      forbidden_tools: ["publish_product"],
      human_handoff_policy: "安全或隐私信号出现时转人工",
      updated_at: "2026-09-01T00:00:00Z",
    },
    {
      item_kind: "SKILL",
      item_ref: "skill:compose:v1",
      logical_id: "skill:compose",
      version: "1.0.0",
      content_hash: HASH_E,
      title: "组合成长产品草案",
      source_lifecycle_state: "RELEASED",
      server_selection_state: "REUSABLE",
      reason_codes: [],
      owner_ref: "product-intelligence",
      purpose: "根据证据与组件生成 DRAFT 配置",
      zone: "ADVANTAGE",
      target_roles: ["PARENT_GUARDIAN"],
      executor_roles: ["PRODUCT_OPERATOR"],
      age_bands: ["AGE_9_12"],
      scenarios: ["PARENT_CHILD_COMMUNICATION"],
      regions: ["CN"],
      locales: ["zh-CN"],
      preconditions: ["evidence_admitted"],
      contraindications: [],
      admission_receipts: [{ receipt_id: "verification-receipt:market", content_hash: HASH_E, outcome: "ADMITTED", policy_version: "admission:v1", valid_until: "2099-09-08T00:00:00Z" }],
      required_skill_refs: [],
      allowed_tools: ["read_component_catalog"],
      forbidden_tools: ["mutate_family_fact"],
      human_handoff_policy: "只生成草案，提交评审前转 Operator",
      updated_at: "2026-09-01T00:00:00Z",
    },
    {
      item_kind: "COMPONENT",
      item_ref: "component:teen-dialogue:v3",
      logical_id: "component:teen-dialogue",
      version: "3.0.0",
      content_hash: HASH_D,
      title: "青少年自主对话",
      source_lifecycle_state: "ACTIVE",
      server_selection_state: "NOT_APPLICABLE",
      reason_codes: ["AGE_MISMATCH", "SCENARIO_MISMATCH"],
      owner_ref: "journey",
      purpose: "支持青少年自主沟通",
      zone: "HOMOGENEOUS",
      target_roles: ["TEEN"],
      executor_roles: ["PRODUCT_OPERATOR"],
      age_bands: ["AGE_13_15"],
      scenarios: ["TEEN_AUTONOMY"],
      regions: ["CN"],
      locales: ["zh-CN"],
      preconditions: ["teen_assent_active"],
      contraindications: ["AGE_9_12"],
      admission_receipts: [{ receipt_id: "verification-receipt:teen", content_hash: HASH_D, outcome: "ADMITTED", policy_version: "admission:v1", valid_until: "2099-09-08T00:00:00Z" }],
      required_skill_refs: [],
      allowed_tools: [],
      forbidden_tools: ["commercial_recommendation"],
      human_handoff_policy: "年龄或同意边界不符时禁止使用",
      updated_at: "2026-09-01T00:00:00Z",
    },
  ],
};
